[package]
name = "manzana-attack"
version = "1.2.0"
authors = ["lislis <mail@lislis.de>"]

[[bin]]
name = "manzana-attack"
path = "src/main.rs"

[dependencies]
piston_window = "0.87.0"
find_folder = "0.3.0"
rand = "0.6.4"

